//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml11
{

    /// <summary>
    /// Choice [0, *]
    ///     ThruLane [0, *]
    ///     PassingLane [0, *]
    ///     TurnLane [0, *]
    ///     TwoWayLeftTurnLane [0, *]
    ///     ClimbLane [0, *]
    ///     OffsetLane [0, *]
    ///     WideningLane [0, *]
    ///     Feature [0, *]
    /// </summary>

    public class Lanes : XsdBaseReader
    {
        public Lanes(System.Xml.XmlReader reader) : base(reader)
        {
        }

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }
            if (name.EqualsIgnoreCase("WideningLane"))
            {
                this.SetCurrent("WideningLane", this.NewReader<WideningLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("OffsetLane"))
            {
                this.SetCurrent("OffsetLane", this.NewReader<OffsetLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("ClimbLane"))
            {
                this.SetCurrent("ClimbLane", this.NewReader<ClimbLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("TwoWayLeftTurnLane"))
            {
                this.SetCurrent("TwoWayLeftTurnLane", this.NewReader<TwoWayLeftTurnLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("TurnLane"))
            {
                this.SetCurrent("TurnLane", this.NewReader<TurnLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("PassingLane"))
            {
                this.SetCurrent("PassingLane", this.NewReader<PassingLane>());
                return true;
            }
            if (name.EqualsIgnoreCase("ThruLane"))
            {
                this.SetCurrent("ThruLane", this.NewReader<ThruLane>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            return buff.ToString();
        }

        #endregion
    }
}
#endif
