//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml11
{

    /// <summary>
    /// Choice [0, *]
    ///     ObstructionOffset [0, *]
    ///     BikeFacilities [0, *]
    ///     RoadSign [0, *]
    ///     DrivewayDensity [0, *]
    ///     HazardRating [0, *]
    ///     Ditch [0, *]
    ///     Feature [0, *]
    /// </summary>

    public class Roadside : XsdBaseReader
    {
        public Roadside(System.Xml.XmlReader reader) : base(reader)
        {
        }

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }
            if (name.EqualsIgnoreCase("Ditch"))
            {
                this.SetCurrent("Ditch", this.NewReader<Ditch>());
                return true;
            }
            if (name.EqualsIgnoreCase("HazardRating"))
            {
                this.SetCurrent("HazardRating", this.NewReader<HazardRating>());
                return true;
            }
            if (name.EqualsIgnoreCase("DrivewayDensity"))
            {
                this.SetCurrent("DrivewayDensity", this.NewReader<DrivewayDensity>());
                return true;
            }
            if (name.EqualsIgnoreCase("RoadSign"))
            {
                this.SetCurrent("RoadSign", this.NewReader<RoadSign>());
                return true;
            }
            if (name.EqualsIgnoreCase("BikeFacilities"))
            {
                this.SetCurrent("BikeFacilities", this.NewReader<BikeFacilities>());
                return true;
            }
            if (name.EqualsIgnoreCase("ObstructionOffset"))
            {
                this.SetCurrent("ObstructionOffset", this.NewReader<ObstructionOffset>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            return buff.ToString();
        }

        #endregion
    }
}
#endif
