//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml11
{

    /// <summary>
    /// The collection of data that was used to create the surface.
    /// Sequence [1, *]
    ///     Choice [1, 1]
    ///         Chain [0, *]
    ///         PointFiles [0, *]
    ///         Boundaries [0, *]
    ///         Breaklines [0, *]
    ///         Contours [0, *]
    ///         DataPoints [0, *]
    ///     Feature [0, *]
    /// </summary>

    public class SourceData : XsdBaseReader
    {
        public SourceData(System.Xml.XmlReader reader) : base(reader)
        {
        }

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }
            if (name.EqualsIgnoreCase("DataPoints"))
            {
                this.SetCurrent("DataPoints", this.NewReader<DataPoints>());
                return true;
            }
            if (name.EqualsIgnoreCase("Contours"))
            {
                this.SetCurrent("Contours", this.NewReader<Contours>());
                return true;
            }
            if (name.EqualsIgnoreCase("Breaklines"))
            {
                this.SetCurrent("Breaklines", this.NewReader<Breaklines>());
                return true;
            }
            if (name.EqualsIgnoreCase("Boundaries"))
            {
                this.SetCurrent("Boundaries", this.NewReader<Boundaries>());
                return true;
            }
            if (name.EqualsIgnoreCase("PointFiles"))
            {
                this.SetCurrent("PointFiles", this.NewReader<PointFiles>());
                return true;
            }
            if (name.EqualsIgnoreCase("Chain"))
            {
                this.SetCurrent("Chain", this.NewReader<Chain>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            return buff.ToString();
        }

        #endregion
    }
}
#endif
