//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml10
{

    /// <summary>
    /// Sequence [1, 1]
    ///     Feature [0, *]
    /// </summary>

    public class CircStruct : XsdBaseReader
    {
        public CircStruct(System.Xml.XmlReader reader) : base(reader)
        {
        }

        public double Diameter;

        public string Desc;

        public string InletCase;

        public double? LossCoeff;

        public string Material;

        public double? Thickness;

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            this.Diameter = XsdConverter.Instance.Convert<double>(
                    attributes.GetSafe("diameter"));

            this.Desc = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("desc"));

            this.InletCase = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("inletCase"));

            this.LossCoeff = XsdConverter.Instance.Convert<double?>(
                    attributes.GetSafe("lossCoeff"));

            this.Material = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("material"));

            this.Thickness = XsdConverter.Instance.Convert<double?>(
                    attributes.GetSafe("thickness"));

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            if ((object)this.Diameter != null)
            {
                buff.Append("diameter", this.Diameter);
            }
            if ((object)this.Desc != null)
            {
                buff.Append("desc", this.Desc);
            }
            if ((object)this.InletCase != null)
            {
                buff.Append("inletCase", this.InletCase);
            }
            if ((object)this.LossCoeff != null)
            {
                buff.Append("lossCoeff", this.LossCoeff);
            }
            if ((object)this.Material != null)
            {
                buff.Append("material", this.Material);
            }
            if ((object)this.Thickness != null)
            {
                buff.Append("thickness", this.Thickness);
            }

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            if ((object)this.Diameter != null)
            {
                buff.AppendFormat("diameter = {0}", this.Diameter).AppendLine();
            }
            if ((object)this.Desc != null)
            {
                buff.AppendFormat("desc = {0}", this.Desc).AppendLine();
            }
            if ((object)this.InletCase != null)
            {
                buff.AppendFormat("inletCase = {0}", this.InletCase).AppendLine();
            }
            if ((object)this.LossCoeff != null)
            {
                buff.AppendFormat("lossCoeff = {0}", this.LossCoeff).AppendLine();
            }
            if ((object)this.Material != null)
            {
                buff.AppendFormat("material = {0}", this.Material).AppendLine();
            }
            if ((object)this.Thickness != null)
            {
                buff.AppendFormat("thickness = {0}", this.Thickness).AppendLine();
            }

            return buff.ToString();
        }

        #endregion
    }
}
#endif
