//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Collections.Generic;
using XmlSchemaProcessor.Processors;

namespace XmlSchemaProcessor.LandXml10
{

    public enum MetPressure
    {
        [StringValue("HPA")]
        HPA,
        [StringValue("milliBars")]
        MilliBars,
        [StringValue("mmHG")]
        MmHG,
        [StringValue("millimeterHG")]
        MillimeterHG,

    }
}
#endif
