//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml12
{

    /// <summary>
    /// A sequential list of Line and/or Curve and/or Spiral elements.
    /// After the sequential list of elements an optional vertical geometry 
    ///    may be defined as a profile, which may be as simple as a list of PVIs (point to point 3D line string).
    /// Sequence [1, 1]
    ///     Choice [1, *]
    ///         Line [0, *]
    ///         IrregularLine [0, *]
    ///         Curve [0, *]
    ///         Spiral [0, *]
    ///         Chain [0, *]
    ///     Feature [0, *]
    /// </summary>

    public class CoordGeom : XsdBaseReader
    {
        public CoordGeom(System.Xml.XmlReader reader) : base(reader)
        {
        }

        public string Desc;

        public string Name;

        public StateType? State;

        public string OID;

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }
            if (name.EqualsIgnoreCase("Chain"))
            {
                this.SetCurrent("Chain", this.NewReader<Chain>());
                return true;
            }
            if (name.EqualsIgnoreCase("Spiral"))
            {
                this.SetCurrent("Spiral", this.NewReader<Spiral>());
                return true;
            }
            if (name.EqualsIgnoreCase("Curve"))
            {
                this.SetCurrent("Curve", this.NewReader<Curve>());
                return true;
            }
            if (name.EqualsIgnoreCase("IrregularLine"))
            {
                this.SetCurrent("IrregularLine", this.NewReader<IrregularLine>());
                return true;
            }
            if (name.EqualsIgnoreCase("Line"))
            {
                this.SetCurrent("Line", this.NewReader<Line>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            this.Desc = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("desc"));

            this.Name = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("name"));

            this.State = XsdConverter.Instance.Convert<StateType?>(
                    attributes.GetSafe("state"));

            this.OID = XsdConverter.Instance.Convert<string>(
                    attributes.GetSafe("oID"));

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            if ((object)this.Desc != null)
            {
                buff.Append("desc", this.Desc);
            }
            if ((object)this.Name != null)
            {
                buff.Append("name", this.Name);
            }
            if ((object)this.State != null)
            {
                buff.Append("state", this.State);
            }
            if ((object)this.OID != null)
            {
                buff.Append("oID", this.OID);
            }

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            if ((object)this.Desc != null)
            {
                buff.AppendFormat("desc = {0}", this.Desc).AppendLine();
            }
            if ((object)this.Name != null)
            {
                buff.AppendFormat("name = {0}", this.Name).AppendLine();
            }
            if ((object)this.State != null)
            {
                buff.AppendFormat("state = {0}", this.State).AppendLine();
            }
            if ((object)this.OID != null)
            {
                buff.AppendFormat("oID = {0}", this.OID).AppendLine();
            }

            return buff.ToString();
        }

        #endregion
    }
}
#endif
