//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml12
{

    public enum ManeuverType
    {
        [StringValue("A-stop-on-rural-road")]
        AStopOnRuralRoad,
        [StringValue("C-speed-path-direction-change-on-rural-road")]
        CSpeedPathDirectionChangeOnRuralRoad,

    }
}
#endif
