//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml12
{

    public enum ZoneMaterialType
    {
        [StringValue("pavement-high-type")]
        PavementHighType,
        [StringValue("pavement-intermediate-type")]
        PavementIntermediateType,
        [StringValue("pavement-low-type")]
        PavementLowType,
        [StringValue("soil")]
        Soil,
        [StringValue("concrete")]
        Concrete,
        [StringValue("stone")]
        Stone,
        [StringValue("riprap")]
        Riprap,
        [StringValue("turf")]
        Turf,
        [StringValue("gravel")]
        Gravel,
        [StringValue("paved")]
        Paved,
        [StringValue("metal")]
        Metal,
        [StringValue("metal grate")]
        MetalGrate,
        [StringValue("composite")]
        Composite,
        [StringValue("timber")]
        Timber,
        [StringValue("other")]
        Other,

    }
}
#endif
