//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml20
{

    /// <summary>
    /// A Single Alignment PI Definition
    /// Choice [1, *]
    ///     Station [1, 1]
    ///     PI [1, 1]
    ///     InSpiral [0, 1]
    ///     Curve1 [0, 1]
    ///     ConnSpiral [0, 1]
    ///     Curve2 [0, 1]
    ///     OutSpiral [0, 1]
    /// </summary>

    public class AlignPI : XsdBaseReader
    {
        public AlignPI(System.Xml.XmlReader reader) : base(reader)
        {
        }

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("OutSpiral"))
            {
                this.SetCurrent("OutSpiral", this.NewReader<OutSpiral>());
                return true;
            }
            if (name.EqualsIgnoreCase("Curve2"))
            {
                this.SetCurrent("Curve2", this.NewReader<Curve2>());
                return true;
            }
            if (name.EqualsIgnoreCase("ConnSpiral"))
            {
                this.SetCurrent("ConnSpiral", this.NewReader<ConnSpiral>());
                return true;
            }
            if (name.EqualsIgnoreCase("Curve1"))
            {
                this.SetCurrent("Curve1", this.NewReader<Curve1>());
                return true;
            }
            if (name.EqualsIgnoreCase("InSpiral"))
            {
                this.SetCurrent("InSpiral", this.NewReader<InSpiral>());
                return true;
            }
            if (name.EqualsIgnoreCase("PI"))
            {
                this.SetCurrent("PI", this.NewReader<PointType>());
                return true;
            }
            if (name.EqualsIgnoreCase("Station"))
            {
                this.SetCurrent("Station", this.NewReader<double>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            return buff.ToString();
        }

        #endregion
    }
}
#endif
