#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Collections.Generic;
using XmlSchemaProcessor.Processors;

namespace XmlSchemaProcessor.LandXml20
{

    public class LandXmlReader : SimpleReader
    {
        public LandXmlReader(ILandXmlEvents events)
            : base("http://www.landxml.org/schema/LandXML-2.0", "http://www.landxml.org/schema/LandXML-1.2", "http://www.landxml.org/schema/LandXML-1.1", "http://www.landxml.org/schema/LandXML-1.0")
        {
            this.Register<IList<double>>("PntList2D",
                    events.BeginReadPntList2D,
                    events.EndReadPntList2D,
                    true);
            this.Register<IList<double>>("PntList3D",
                    events.BeginReadPntList3D,
                    events.EndReadPntList3D,
                    true);
            this.Register<byte[]>("TextureHexString",
                    events.BeginReadTextureHexString,
                    events.EndReadTextureHexString,
                    true);
            this.Register<byte[]>("SymbolHexString",
                    events.BeginReadSymbolHexString,
                    events.EndReadSymbolHexString,
                    true);
            this.Register<byte[]>("SymbolMtlHexString",
                    events.BeginReadSymbolMtlHexString,
                    events.EndReadSymbolMtlHexString,
                    true);
            this.Register<string>("TextureImageNameRef",
                    events.BeginReadTextureImageNameRef,
                    events.EndReadTextureImageNameRef,
                    true);
            this.Register<double>("BeginRunoutSta",
                    events.BeginReadBeginRunoutSta,
                    events.EndReadBeginRunoutSta,
                    true);
            this.Register<double>("BeginRunoffSta",
                    events.BeginReadBeginRunoffSta,
                    events.EndReadBeginRunoffSta,
                    true);
            this.Register<double>("FullSuperSta",
                    events.BeginReadFullSuperSta,
                    events.EndReadFullSuperSta,
                    true);
            this.Register<double>("FullSuperelev",
                    events.BeginReadFullSuperelev,
                    events.EndReadFullSuperelev,
                    true);
            this.Register<double>("RunoffSta",
                    events.BeginReadRunoffSta,
                    events.EndReadRunoffSta,
                    true);
            this.Register<double>("StartofRunoutSta",
                    events.BeginReadStartofRunoutSta,
                    events.EndReadStartofRunoutSta,
                    true);
            this.Register<double>("EndofRunoutSta",
                    events.BeginReadEndofRunoutSta,
                    events.EndReadEndofRunoutSta,
                    true);
            this.Register<AdverseSEType>("AdverseSE",
                    events.BeginReadAdverseSE,
                    events.EndReadAdverseSE,
                    true);
            this.Register<double>("Station",
                    events.BeginReadStation,
                    events.EndReadStation,
                    true);
            this.Register<LandXML>("LandXML",
                    events.BeginReadLandXML,
                    events.EndReadLandXML,
                    false);
            this.Register<CgPoints>("CgPoints",
                    events.BeginReadCgPoints,
                    events.EndReadCgPoints,
                    false);
            this.Register<CgPoint>("CgPoint",
                    events.BeginReadCgPoint,
                    events.EndReadCgPoint,
                    false);
            this.Register<DocFileRef>("DocFileRef",
                    events.BeginReadDocFileRef,
                    events.EndReadDocFileRef,
                    false);
            this.Register<Property>("Property",
                    events.BeginReadProperty,
                    events.EndReadProperty,
                    false);
            this.Register<Feature>("Feature",
                    events.BeginReadFeature,
                    events.EndReadFeature,
                    false);
            this.Register<FeatureDictionary>("FeatureDictionary",
                    events.BeginReadFeatureDictionary,
                    events.EndReadFeatureDictionary,
                    false);
            this.Register<PointType>("Start",
                    events.BeginReadStart,
                    events.EndReadStart,
                    false);
            this.Register<PointType>("End",
                    events.BeginReadEnd,
                    events.EndReadEnd,
                    false);
            this.Register<PointType>("Center",
                    events.BeginReadCenter,
                    events.EndReadCenter,
                    false);
            this.Register<PointType>("PI",
                    events.BeginReadPI,
                    events.EndReadPI,
                    false);
            this.Register<PointType>("MapPoint",
                    events.BeginReadMapPoint,
                    events.EndReadMapPoint,
                    false);
            this.Register<PointType>("InstrumentPoint",
                    events.BeginReadInstrumentPoint,
                    events.EndReadInstrumentPoint,
                    false);
            this.Register<PointType>("Location",
                    events.BeginReadLocation,
                    events.EndReadLocation,
                    false);
            this.Register<IrregularLine>("IrregularLine",
                    events.BeginReadIrregularLine,
                    events.EndReadIrregularLine,
                    false);
            this.Register<Chain>("Chain",
                    events.BeginReadChain,
                    events.EndReadChain,
                    false);
            this.Register<Curve>("Curve",
                    events.BeginReadCurve,
                    events.EndReadCurve,
                    false);
            this.Register<Spiral>("Spiral",
                    events.BeginReadSpiral,
                    events.EndReadSpiral,
                    false);
            this.Register<CoordGeom>("CoordGeom",
                    events.BeginReadCoordGeom,
                    events.EndReadCoordGeom,
                    false);
            this.Register<Line>("Line",
                    events.BeginReadLine,
                    events.EndReadLine,
                    false);
            this.Register<CrossSects>("CrossSects",
                    events.BeginReadCrossSects,
                    events.EndReadCrossSects,
                    false);
            this.Register<CrossSect>("CrossSect",
                    events.BeginReadCrossSect,
                    events.EndReadCrossSect,
                    false);
            this.Register<CrossSectSurf>("CrossSectSurf",
                    events.BeginReadCrossSectSurf,
                    events.EndReadCrossSectSurf,
                    false);
            this.Register<CrossSectPnt>("CrossSectPnt",
                    events.BeginReadCrossSectPnt,
                    events.EndReadCrossSectPnt,
                    false);
            this.Register<DesignCrossSectionTemplateTable>("DesignCrossSectionTemplateTable",
                    events.BeginReadDesignCrossSectionTemplateTable,
                    events.EndReadDesignCrossSectionTemplateTable,
                    false);
            this.Register<DesignCrossSectionTemplate>("DesignCrossSectionTemplate",
                    events.BeginReadDesignCrossSectionTemplate,
                    events.EndReadDesignCrossSectionTemplate,
                    false);
            this.Register<DesignCrossSectSurf>("DesignCrossSectSurf",
                    events.BeginReadDesignCrossSectSurf,
                    events.EndReadDesignCrossSectSurf,
                    false);
            this.Register<Project>("Project",
                    events.BeginReadProject,
                    events.EndReadProject,
                    false);
            this.Register<Units>("Units",
                    events.BeginReadUnits,
                    events.EndReadUnits,
                    false);
            this.Register<Metric>("Metric",
                    events.BeginReadMetric,
                    events.EndReadMetric,
                    false);
            this.Register<Imperial>("Imperial",
                    events.BeginReadImperial,
                    events.EndReadImperial,
                    false);
            this.Register<CoordinateSystem>("CoordinateSystem",
                    events.BeginReadCoordinateSystem,
                    events.EndReadCoordinateSystem,
                    false);
            this.Register<Application>("Application",
                    events.BeginReadApplication,
                    events.EndReadApplication,
                    false);
            this.Register<Author>("Author",
                    events.BeginReadAuthor,
                    events.EndReadAuthor,
                    false);
            this.Register<Survey>("Survey",
                    events.BeginReadSurvey,
                    events.EndReadSurvey,
                    false);
            this.Register<SurveyHeader>("SurveyHeader",
                    events.BeginReadSurveyHeader,
                    events.EndReadSurveyHeader,
                    false);
            this.Register<HeadOfPower>("HeadOfPower",
                    events.BeginReadHeadOfPower,
                    events.EndReadHeadOfPower,
                    false);
            this.Register<AdministrativeArea>("AdministrativeArea",
                    events.BeginReadAdministrativeArea,
                    events.EndReadAdministrativeArea,
                    false);
            this.Register<AdministrativeDate>("AdministrativeDate",
                    events.BeginReadAdministrativeDate,
                    events.EndReadAdministrativeDate,
                    false);
            this.Register<Annotation>("Annotation",
                    events.BeginReadAnnotation,
                    events.EndReadAnnotation,
                    false);
            this.Register<SurveyorCertificate>("SurveyorCertificate",
                    events.BeginReadSurveyorCertificate,
                    events.EndReadSurveyorCertificate,
                    false);
            this.Register<PurposeOfSurvey>("PurposeOfSurvey",
                    events.BeginReadPurposeOfSurvey,
                    events.EndReadPurposeOfSurvey,
                    false);
            this.Register<Amendment>("Amendment",
                    events.BeginReadAmendment,
                    events.EndReadAmendment,
                    false);
            this.Register<AmendmentItem>("AmendmentItem",
                    events.BeginReadAmendmentItem,
                    events.EndReadAmendmentItem,
                    false);
            this.Register<Personnel>("Personnel",
                    events.BeginReadPersonnel,
                    events.EndReadPersonnel,
                    false);
            this.Register<FieldNote>("FieldNote",
                    events.BeginReadFieldNote,
                    events.EndReadFieldNote,
                    false);
            this.Register<Equipment>("Equipment",
                    events.BeginReadEquipment,
                    events.EndReadEquipment,
                    false);
            this.Register<InstrumentDetails>("InstrumentDetails",
                    events.BeginReadInstrumentDetails,
                    events.EndReadInstrumentDetails,
                    false);
            this.Register<LaserDetails>("LaserDetails",
                    events.BeginReadLaserDetails,
                    events.EndReadLaserDetails,
                    false);
            this.Register<GPSAntennaDetails>("GPSAntennaDetails",
                    events.BeginReadGPSAntennaDetails,
                    events.EndReadGPSAntennaDetails,
                    false);
            this.Register<GPSReceiverDetails>("GPSReceiverDetails",
                    events.BeginReadGPSReceiverDetails,
                    events.EndReadGPSReceiverDetails,
                    false);
            this.Register<Corrections>("Corrections",
                    events.BeginReadCorrections,
                    events.EndReadCorrections,
                    false);
            this.Register<SurveyMonument>("SurveyMonument",
                    events.BeginReadSurveyMonument,
                    events.EndReadSurveyMonument,
                    false);
            this.Register<InstrumentSetup>("InstrumentSetup",
                    events.BeginReadInstrumentSetup,
                    events.EndReadInstrumentSetup,
                    false);
            this.Register<LaserSetup>("LaserSetup",
                    events.BeginReadLaserSetup,
                    events.EndReadLaserSetup,
                    false);
            this.Register<GPSSetup>("GPSSetup",
                    events.BeginReadGPSSetup,
                    events.EndReadGPSSetup,
                    false);
            this.Register<TargetSetup>("TargetSetup",
                    events.BeginReadTargetSetup,
                    events.EndReadTargetSetup,
                    false);
            this.Register<Backsight>("Backsight",
                    events.BeginReadBacksight,
                    events.EndReadBacksight,
                    false);
            this.Register<RawObservation>("RawObservation",
                    events.BeginReadRawObservation,
                    events.EndReadRawObservation,
                    false);
            this.Register<TestObservation>("TestObservation",
                    events.BeginReadTestObservation,
                    events.EndReadTestObservation,
                    false);
            this.Register<PointType>("TargetPoint",
                    events.BeginReadTargetPoint,
                    events.EndReadTargetPoint,
                    false);
            this.Register<PointType>("BacksightPoint",
                    events.BeginReadBacksightPoint,
                    events.EndReadBacksightPoint,
                    false);
            this.Register<OffsetVals>("OffsetVals",
                    events.BeginReadOffsetVals,
                    events.EndReadOffsetVals,
                    false);
            this.Register<GPSVector>("GPSVector",
                    events.BeginReadGPSVector,
                    events.EndReadGPSVector,
                    false);
            this.Register<GPSPosition>("GPSPosition",
                    events.BeginReadGPSPosition,
                    events.EndReadGPSPosition,
                    false);
            this.Register<GPSQCInfoLevel1>("GPSQCInfoLevel1",
                    events.BeginReadGPSQCInfoLevel1,
                    events.EndReadGPSQCInfoLevel1,
                    false);
            this.Register<GPSQCInfoLevel2>("GPSQCInfoLevel2",
                    events.BeginReadGPSQCInfoLevel2,
                    events.EndReadGPSQCInfoLevel2,
                    false);
            this.Register<ObservationGroup>("ObservationGroup",
                    events.BeginReadObservationGroup,
                    events.EndReadObservationGroup,
                    false);
            this.Register<ControlChecks>("ControlChecks",
                    events.BeginReadControlChecks,
                    events.EndReadControlChecks,
                    false);
            this.Register<PointResults>("PointResults",
                    events.BeginReadPointResults,
                    events.EndReadPointResults,
                    false);
            this.Register<ReducedObservation>("ReducedObservation",
                    events.BeginReadReducedObservation,
                    events.EndReadReducedObservation,
                    false);
            this.Register<ReducedArcObservation>("ReducedArcObservation",
                    events.BeginReadReducedArcObservation,
                    events.EndReadReducedArcObservation,
                    false);
            this.Register<RedHorizontalPosition>("RedHorizontalPosition",
                    events.BeginReadRedHorizontalPosition,
                    events.EndReadRedHorizontalPosition,
                    false);
            this.Register<RedVerticalObservation>("RedVerticalObservation",
                    events.BeginReadRedVerticalObservation,
                    events.EndReadRedVerticalObservation,
                    false);
            this.Register<Monuments>("Monuments",
                    events.BeginReadMonuments,
                    events.EndReadMonuments,
                    false);
            this.Register<Monument>("Monument",
                    events.BeginReadMonument,
                    events.EndReadMonument,
                    false);
            this.Register<TextureImage>("TextureImage",
                    events.BeginReadTextureImage,
                    events.EndReadTextureImage,
                    false);
            this.Register<Symbol>("Symbol",
                    events.BeginReadSymbol,
                    events.EndReadSymbol,
                    false);
            this.Register<Material>("Material",
                    events.BeginReadMaterial,
                    events.EndReadMaterial,
                    false);
            this.Register<MaterialTable>("MaterialTable",
                    events.BeginReadMaterialTable,
                    events.EndReadMaterialTable,
                    false);
            this.Register<TextureImageTable>("TextureImageTable",
                    events.BeginReadTextureImageTable,
                    events.EndReadTextureImageTable,
                    false);
            this.Register<SymbolTable>("SymbolTable",
                    events.BeginReadSymbolTable,
                    events.EndReadSymbolTable,
                    false);
            this.Register<Surfaces>("Surfaces",
                    events.BeginReadSurfaces,
                    events.EndReadSurfaces,
                    false);
            this.Register<Surface>("Surface",
                    events.BeginReadSurface,
                    events.EndReadSurface,
                    false);
            this.Register<SourceData>("SourceData",
                    events.BeginReadSourceData,
                    events.EndReadSourceData,
                    false);
            this.Register<DataPoints>("DataPoints",
                    events.BeginReadDataPoints,
                    events.EndReadDataPoints,
                    false);
            this.Register<PointFiles>("PointFiles",
                    events.BeginReadPointFiles,
                    events.EndReadPointFiles,
                    false);
            this.Register<PointFile>("PointFile",
                    events.BeginReadPointFile,
                    events.EndReadPointFile,
                    false);
            this.Register<Boundaries>("Boundaries",
                    events.BeginReadBoundaries,
                    events.EndReadBoundaries,
                    false);
            this.Register<Boundary>("Boundary",
                    events.BeginReadBoundary,
                    events.EndReadBoundary,
                    false);
            this.Register<Breaklines>("Breaklines",
                    events.BeginReadBreaklines,
                    events.EndReadBreaklines,
                    false);
            this.Register<Breakline>("Breakline",
                    events.BeginReadBreakline,
                    events.EndReadBreakline,
                    false);
            this.Register<RetWall>("RetWall",
                    events.BeginReadRetWall,
                    events.EndReadRetWall,
                    false);
            this.Register<RetWallPnt>("RetWallPnt",
                    events.BeginReadRetWallPnt,
                    events.EndReadRetWallPnt,
                    false);
            this.Register<Contours>("Contours",
                    events.BeginReadContours,
                    events.EndReadContours,
                    false);
            this.Register<Contour>("Contour",
                    events.BeginReadContour,
                    events.EndReadContour,
                    false);
            this.Register<Definition>("Definition",
                    events.BeginReadDefinition,
                    events.EndReadDefinition,
                    false);
            this.Register<Pnts>("Pnts",
                    events.BeginReadPnts,
                    events.EndReadPnts,
                    false);
            this.Register<P>("P",
                    events.BeginReadP,
                    events.EndReadP,
                    false);
            this.Register<Faces>("Faces",
                    events.BeginReadFaces,
                    events.EndReadFaces,
                    false);
            this.Register<F>("F",
                    events.BeginReadF,
                    events.EndReadF,
                    false);
            this.Register<Watersheds>("Watersheds",
                    events.BeginReadWatersheds,
                    events.EndReadWatersheds,
                    false);
            this.Register<Watershed>("Watershed",
                    events.BeginReadWatershed,
                    events.EndReadWatershed,
                    false);
            this.Register<Outlet>("Outlet",
                    events.BeginReadOutlet,
                    events.EndReadOutlet,
                    false);
            this.Register<SurfVolumes>("SurfVolumes",
                    events.BeginReadSurfVolumes,
                    events.EndReadSurfVolumes,
                    false);
            this.Register<SurfVolume>("SurfVolume",
                    events.BeginReadSurfVolume,
                    events.EndReadSurfVolume,
                    false);
            this.Register<Parcels>("Parcels",
                    events.BeginReadParcels,
                    events.EndReadParcels,
                    false);
            this.Register<Parcel>("Parcel",
                    events.BeginReadParcel,
                    events.EndReadParcel,
                    false);
            this.Register<VolumeGeom>("VolumeGeom",
                    events.BeginReadVolumeGeom,
                    events.EndReadVolumeGeom,
                    false);
            this.Register<Title>("Title",
                    events.BeginReadTitle,
                    events.EndReadTitle,
                    false);
            this.Register<Exclusions>("Exclusions",
                    events.BeginReadExclusions,
                    events.EndReadExclusions,
                    false);
            this.Register<LocationAddress>("LocationAddress",
                    events.BeginReadLocationAddress,
                    events.EndReadLocationAddress,
                    false);
            this.Register<ComplexName>("ComplexName",
                    events.BeginReadComplexName,
                    events.EndReadComplexName,
                    false);
            this.Register<RoadName>("RoadName",
                    events.BeginReadRoadName,
                    events.EndReadRoadName,
                    false);
            this.Register<AddressPoint>("AddressPoint",
                    events.BeginReadAddressPoint,
                    events.EndReadAddressPoint,
                    false);
            this.Register<Alignments>("Alignments",
                    events.BeginReadAlignments,
                    events.EndReadAlignments,
                    false);
            this.Register<Alignment>("Alignment",
                    events.BeginReadAlignment,
                    events.EndReadAlignment,
                    false);
            this.Register<StaEquation>("StaEquation",
                    events.BeginReadStaEquation,
                    events.EndReadStaEquation,
                    false);
            this.Register<Profile>("Profile",
                    events.BeginReadProfile,
                    events.EndReadProfile,
                    false);
            this.Register<ProfSurf>("ProfSurf",
                    events.BeginReadProfSurf,
                    events.EndReadProfSurf,
                    false);
            this.Register<ProfAlign>("ProfAlign",
                    events.BeginReadProfAlign,
                    events.EndReadProfAlign,
                    false);
            this.Register<PVI>("PVI",
                    events.BeginReadPVI,
                    events.EndReadPVI,
                    false);
            this.Register<ParaCurve>("ParaCurve",
                    events.BeginReadParaCurve,
                    events.EndReadParaCurve,
                    false);
            this.Register<UnsymParaCurve>("UnsymParaCurve",
                    events.BeginReadUnsymParaCurve,
                    events.EndReadUnsymParaCurve,
                    false);
            this.Register<CircCurve>("CircCurve",
                    events.BeginReadCircCurve,
                    events.EndReadCircCurve,
                    false);
            this.Register<PipeNetworks>("PipeNetworks",
                    events.BeginReadPipeNetworks,
                    events.EndReadPipeNetworks,
                    false);
            this.Register<PipeNetwork>("PipeNetwork",
                    events.BeginReadPipeNetwork,
                    events.EndReadPipeNetwork,
                    false);
            this.Register<Pipes>("Pipes",
                    events.BeginReadPipes,
                    events.EndReadPipes,
                    false);
            this.Register<Pipe>("Pipe",
                    events.BeginReadPipe,
                    events.EndReadPipe,
                    false);
            this.Register<CircPipe>("CircPipe",
                    events.BeginReadCircPipe,
                    events.EndReadCircPipe,
                    false);
            this.Register<ElliPipe>("ElliPipe",
                    events.BeginReadElliPipe,
                    events.EndReadElliPipe,
                    false);
            this.Register<EggPipe>("EggPipe",
                    events.BeginReadEggPipe,
                    events.EndReadEggPipe,
                    false);
            this.Register<RectPipe>("RectPipe",
                    events.BeginReadRectPipe,
                    events.EndReadRectPipe,
                    false);
            this.Register<Channel>("Channel",
                    events.BeginReadChannel,
                    events.EndReadChannel,
                    false);
            this.Register<Pond>("Pond",
                    events.BeginReadPond,
                    events.EndReadPond,
                    false);
            this.Register<PipeFlow>("PipeFlow",
                    events.BeginReadPipeFlow,
                    events.EndReadPipeFlow,
                    false);
            this.Register<Structs>("Structs",
                    events.BeginReadStructs,
                    events.EndReadStructs,
                    false);
            this.Register<Struct>("Struct",
                    events.BeginReadStruct,
                    events.EndReadStruct,
                    false);
            this.Register<CircStruct>("CircStruct",
                    events.BeginReadCircStruct,
                    events.EndReadCircStruct,
                    false);
            this.Register<RectStruct>("RectStruct",
                    events.BeginReadRectStruct,
                    events.EndReadRectStruct,
                    false);
            this.Register<InletStruct>("InletStruct",
                    events.BeginReadInletStruct,
                    events.EndReadInletStruct,
                    false);
            this.Register<OutletStruct>("OutletStruct",
                    events.BeginReadOutletStruct,
                    events.EndReadOutletStruct,
                    false);
            this.Register<Connection>("Connection",
                    events.BeginReadConnection,
                    events.EndReadConnection,
                    false);
            this.Register<Invert>("Invert",
                    events.BeginReadInvert,
                    events.EndReadInvert,
                    false);
            this.Register<StructFlow>("StructFlow",
                    events.BeginReadStructFlow,
                    events.EndReadStructFlow,
                    false);
            this.Register<PlanFeatures>("PlanFeatures",
                    events.BeginReadPlanFeatures,
                    events.EndReadPlanFeatures,
                    false);
            this.Register<PlanFeature>("PlanFeature",
                    events.BeginReadPlanFeature,
                    events.EndReadPlanFeature,
                    false);
            this.Register<GradeModel>("GradeModel",
                    events.BeginReadGradeModel,
                    events.EndReadGradeModel,
                    false);
            this.Register<GradeSurface>("GradeSurface",
                    events.BeginReadGradeSurface,
                    events.EndReadGradeSurface,
                    false);
            this.Register<Zones>("Zones",
                    events.BeginReadZones,
                    events.EndReadZones,
                    false);
            this.Register<Zone>("Zone",
                    events.BeginReadZone,
                    events.EndReadZone,
                    false);
            this.Register<ZoneWidth>("ZoneWidth",
                    events.BeginReadZoneWidth,
                    events.EndReadZoneWidth,
                    false);
            this.Register<ZoneSlope>("ZoneSlope",
                    events.BeginReadZoneSlope,
                    events.EndReadZoneSlope,
                    false);
            this.Register<ZoneHinge>("ZoneHinge",
                    events.BeginReadZoneHinge,
                    events.EndReadZoneHinge,
                    false);
            this.Register<ZoneCutFill>("ZoneCutFill",
                    events.BeginReadZoneCutFill,
                    events.EndReadZoneCutFill,
                    false);
            this.Register<ZoneMaterial>("ZoneMaterial",
                    events.BeginReadZoneMaterial,
                    events.EndReadZoneMaterial,
                    false);
            this.Register<ZoneCrossSectStructure>("ZoneCrossSectStructure",
                    events.BeginReadZoneCrossSectStructure,
                    events.EndReadZoneCrossSectStructure,
                    false);
            this.Register<Roadways>("Roadways",
                    events.BeginReadRoadways,
                    events.EndReadRoadways,
                    false);
            this.Register<Roadway>("Roadway",
                    events.BeginReadRoadway,
                    events.EndReadRoadway,
                    false);
            this.Register<Classification>("Classification",
                    events.BeginReadClassification,
                    events.EndReadClassification,
                    false);
            this.Register<DesignSpeed>("DesignSpeed",
                    events.BeginReadDesignSpeed,
                    events.EndReadDesignSpeed,
                    false);
            this.Register<DesignSpeed85th>("DesignSpeed85th",
                    events.BeginReadDesignSpeed85th,
                    events.EndReadDesignSpeed85th,
                    false);
            this.Register<Speeds>("Speeds",
                    events.BeginReadSpeeds,
                    events.EndReadSpeeds,
                    false);
            this.Register<DailyTrafficVolume>("DailyTrafficVolume",
                    events.BeginReadDailyTrafficVolume,
                    events.EndReadDailyTrafficVolume,
                    false);
            this.Register<DesignHour>("DesignHour",
                    events.BeginReadDesignHour,
                    events.EndReadDesignHour,
                    false);
            this.Register<PeakHour>("PeakHour",
                    events.BeginReadPeakHour,
                    events.EndReadPeakHour,
                    false);
            this.Register<TrafficVolume>("TrafficVolume",
                    events.BeginReadTrafficVolume,
                    events.EndReadTrafficVolume,
                    false);
            this.Register<Superelevation>("Superelevation",
                    events.BeginReadSuperelevation,
                    events.EndReadSuperelevation,
                    false);
            this.Register<Lanes>("Lanes",
                    events.BeginReadLanes,
                    events.EndReadLanes,
                    false);
            this.Register<ThruLane>("ThruLane",
                    events.BeginReadThruLane,
                    events.EndReadThruLane,
                    false);
            this.Register<PassingLane>("PassingLane",
                    events.BeginReadPassingLane,
                    events.EndReadPassingLane,
                    false);
            this.Register<TurnLane>("TurnLane",
                    events.BeginReadTurnLane,
                    events.EndReadTurnLane,
                    false);
            this.Register<TwoWayLeftTurnLane>("TwoWayLeftTurnLane",
                    events.BeginReadTwoWayLeftTurnLane,
                    events.EndReadTwoWayLeftTurnLane,
                    false);
            this.Register<ClimbLane>("ClimbLane",
                    events.BeginReadClimbLane,
                    events.EndReadClimbLane,
                    false);
            this.Register<OffsetLane>("OffsetLane",
                    events.BeginReadOffsetLane,
                    events.EndReadOffsetLane,
                    false);
            this.Register<WideningLane>("WideningLane",
                    events.BeginReadWideningLane,
                    events.EndReadWideningLane,
                    false);
            this.Register<Roadside>("Roadside",
                    events.BeginReadRoadside,
                    events.EndReadRoadside,
                    false);
            this.Register<Ditch>("Ditch",
                    events.BeginReadDitch,
                    events.EndReadDitch,
                    false);
            this.Register<ObstructionOffset>("ObstructionOffset",
                    events.BeginReadObstructionOffset,
                    events.EndReadObstructionOffset,
                    false);
            this.Register<BikeFacilities>("BikeFacilities",
                    events.BeginReadBikeFacilities,
                    events.EndReadBikeFacilities,
                    false);
            this.Register<RoadSign>("RoadSign",
                    events.BeginReadRoadSign,
                    events.EndReadRoadSign,
                    false);
            this.Register<DrivewayDensity>("DrivewayDensity",
                    events.BeginReadDrivewayDensity,
                    events.EndReadDrivewayDensity,
                    false);
            this.Register<HazardRating>("HazardRating",
                    events.BeginReadHazardRating,
                    events.EndReadHazardRating,
                    false);
            this.Register<Intersections>("Intersections",
                    events.BeginReadIntersections,
                    events.EndReadIntersections,
                    false);
            this.Register<Intersection>("Intersection",
                    events.BeginReadIntersection,
                    events.EndReadIntersection,
                    false);
            this.Register<TrafficControl>("TrafficControl",
                    events.BeginReadTrafficControl,
                    events.EndReadTrafficControl,
                    false);
            this.Register<Timing>("Timing",
                    events.BeginReadTiming,
                    events.EndReadTiming,
                    false);
            this.Register<Volume>("Volume",
                    events.BeginReadVolume,
                    events.EndReadVolume,
                    false);
            this.Register<TurnSpeed>("TurnSpeed",
                    events.BeginReadTurnSpeed,
                    events.EndReadTurnSpeed,
                    false);
            this.Register<TurnRestriction>("TurnRestriction",
                    events.BeginReadTurnRestriction,
                    events.EndReadTurnRestriction,
                    false);
            this.Register<Curb>("Curb",
                    events.BeginReadCurb,
                    events.EndReadCurb,
                    false);
            this.Register<Corner>("Corner",
                    events.BeginReadCorner,
                    events.EndReadCorner,
                    false);
            this.Register<CrashData>("CrashData",
                    events.BeginReadCrashData,
                    events.EndReadCrashData,
                    false);
            this.Register<CrashHistory>("CrashHistory",
                    events.BeginReadCrashHistory,
                    events.EndReadCrashHistory,
                    false);
            this.Register<PostedSpeed>("PostedSpeed",
                    events.BeginReadPostedSpeed,
                    events.EndReadPostedSpeed,
                    false);
            this.Register<NoPassingZone>("NoPassingZone",
                    events.BeginReadNoPassingZone,
                    events.EndReadNoPassingZone,
                    false);
            this.Register<DecisionSightDistance>("DecisionSightDistance",
                    events.BeginReadDecisionSightDistance,
                    events.EndReadDecisionSightDistance,
                    false);
            this.Register<BridgeElement>("BridgeElement",
                    events.BeginReadBridgeElement,
                    events.EndReadBridgeElement,
                    false);
            this.Register<InSpiral>("InSpiral",
                    events.BeginReadInSpiral,
                    events.EndReadInSpiral,
                    false);
            this.Register<Curve1>("Curve1",
                    events.BeginReadCurve1,
                    events.EndReadCurve1,
                    false);
            this.Register<ConnSpiral>("ConnSpiral",
                    events.BeginReadConnSpiral,
                    events.EndReadConnSpiral,
                    false);
            this.Register<Curve2>("Curve2",
                    events.BeginReadCurve2,
                    events.EndReadCurve2,
                    false);
            this.Register<OutSpiral>("OutSpiral",
                    events.BeginReadOutSpiral,
                    events.EndReadOutSpiral,
                    false);
            this.Register<AlignPI>("AlignPI",
                    events.BeginReadAlignPI,
                    events.EndReadAlignPI,
                    false);
            this.Register<AlignPIs>("AlignPIs",
                    events.BeginReadAlignPIs,
                    events.EndReadAlignPIs,
                    false);
            this.Register<Cant>("Cant",
                    events.BeginReadCant,
                    events.EndReadCant,
                    false);
            this.Register<CantStation>("CantStation",
                    events.BeginReadCantStation,
                    events.EndReadCantStation,
                    false);
            this.Register<SpeedStation>("SpeedStation",
                    events.BeginReadSpeedStation,
                    events.EndReadSpeedStation,
                    false);

        }
    }
}
#endif

