//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml20
{

    /// <summary>
    /// This indicates the category of a geodetic Monument
    /// </summary>

    public enum MonumentCategory
    {
        [StringValue("benchmark")]
        Benchmark,
        [StringValue("central")]
        Central,
        [StringValue("reference")]
        Reference,
        [StringValue("rural")]
        Rural,
        [StringValue("standard traverse")]
        StandardTraverse,
        [StringValue("urban standard traverse")]
        UrbanStandardTraverse,

    }
}
#endif
