//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Collections.Generic;
using XmlSchemaProcessor.Processors;

namespace XmlSchemaProcessor.LandXml20
{

    public enum RoadSignType
    {
        [StringValue("regulatory")]
        Regulatory,
        [StringValue("guide")]
        Guide,
        [StringValue("warning")]
        Warning,
        [StringValue("specificService")]
        SpecificService,
        [StringValue("tourist")]
        Tourist,
        [StringValue("recreation-cultural")]
        RecreationCultural,
        [StringValue("emergencyManagement")]
        EmergencyManagement,

    }
}
#endif
