//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Collections.Generic;
using XmlSchemaProcessor.Processors;

namespace XmlSchemaProcessor.LandXml20
{

    /// <summary>
    /// TIN is the acronym for "triangulated irregular network", a surface comprised of 3 point faces
    /// grid is a surface comprised of 4 point faces.
    /// </summary>

    public enum SurfTypeEnum
    {
        [StringValue("TIN")]
        TIN,
        [StringValue("grid")]
        Grid,

    }
}
#endif
