//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: <..>
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#if !BUILD_LAND_XML
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using XmlSchemaProcessor.Common;

namespace XmlSchemaProcessor.LandXml20
{

    /// <summary>
    /// Choice [1, *]
    ///     DailyTrafficVolume [1, 1]
    ///     DesignHour [1, 1]
    ///     PeakHour [1, 1]
    ///     Feature [0, *]
    /// </summary>

    public class TrafficVolume : XsdBaseReader
    {
        public TrafficVolume(System.Xml.XmlReader reader) : base(reader)
        {
        }

        #region XsdBaseReader

        protected override bool NewReader(string namespaceURI, string name)
        {
            if (name.EqualsIgnoreCase("Feature"))
            {
                this.SetCurrent("Feature", this.NewReader<Feature>());
                return true;
            }
            if (name.EqualsIgnoreCase("PeakHour"))
            {
                this.SetCurrent("PeakHour", this.NewReader<PeakHour>());
                return true;
            }
            if (name.EqualsIgnoreCase("DesignHour"))
            {
                this.SetCurrent("DesignHour", this.NewReader<DesignHour>());
                return true;
            }
            if (name.EqualsIgnoreCase("DailyTrafficVolume"))
            {
                this.SetCurrent("DailyTrafficVolume", this.NewReader<DailyTrafficVolume>());
                return true;
            }

            return base.NewReader(namespaceURI, name);
        }

        #endregion

        #region XsdBaseObject

        public override bool Read(IDictionary<string, string> attributes, string text)
        {
            base.Read(attributes, text);

            return true;
        }

        public override string ToAttributes()
        {
            AttributesBuilder buff = new AttributesBuilder(base.ToAttributes());

            return buff.ToString();
        }

        #endregion

        #region object

        public override string ToString()
        {
            StringBuilder buff = new StringBuilder(base.ToString());

            return buff.ToString();
        }

        #endregion
    }
}
#endif
